<a href="https://colab.research.google.com/github/PariaNajafi/Neural_Network_Learning/blob/main/Neural_Network_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

23 اسفند

first install tensorflow to code local,
<br>
!pip install tensorflow
<br>
if u use conda
<br>
!conda install tensorflow


to use different versions of packages must make an environment in conda.
<br>
! conda create -n env_name
<br>
install conda environment:  

https://docs.conda.io/projects/conda/en/stable/commands/env/create.html

tensorflow vesions:

https://www.tensorflow.org/versions


https://colab.research.google.com/github/smsrikanthreddy/blog/blob/master/_notebooks/2021-06-01-How%20to%20create%20environment%20in%20Python.ipynb#scrollTo=gross-tissue

keras website:(with a good docs)

(https://keras.io)

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

show off colabs internet speed

linux commands could used with bang ! in colab and jupiter...

in Iran now the speed is under 10 MBps, and in colab is 147MBps and colab downloads 1G in 8.2s.

we can use for download kagel datasets and send it to google drive and download it without unti filter in Iran

In [3]:
! wget https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Windows-x86_64.exe

--2024-03-22 16:14:44--  https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Windows-x86_64.exe
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 948300296 (904M) [application/octet-stream]
Saving to: ‘Anaconda3-2024.02-1-Windows-x86_64.exe’

Anaconda3-2024.02-1 100%[===================>] 904.37M   147MB/s    in 8.2s    

2024-03-22 16:14:53 (111 MB/s) - ‘Anaconda3-2024.02-1-Windows-x86_64.exe’ saved [948300296/948300296]



design the model we made later with tf:
we wanna make a sequential model with sequential class.
non sequential models will described

In [4]:
model = tf.keras.models.Sequential()

In [8]:
model.add(tf.keras.layers.Dense(units=3, input_shape=(3,)))

In [19]:
#shape_size is must be a tuple because in code it is added with a tuple
# batch_input_shape = (batch_size,) + tuple(kwargs["input_shape"])
#you will get an error when u use like this --> input_shape=(3)
# if your input is linear and it is just a syntax
#units =neurons, input_shapes= features
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.models import Sequential


In [12]:
model = Sequential()
model.add(Dense(3, input_shape=(5,)))

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 3)                 18        
                                                                 
Total params: 18 (72.00 Byte)
Trainable params: 18 (72.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


neurons of last layer =output_shape

batch = none

pqaram = 18 = 3(neurons)*5(input,features) +3(bias)

## multi layer perceptron :

In [14]:
model = Sequential()
model.add(Dense(4, input_shape=(4,)))
model.add(Dense(3))
# input shape just is useful in first layer , input layer, other layers get input layer from Previous layer

In [16]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 4)                 20        
                                                                 
 dense_5 (Dense)             (None, 3)                 15        
                                                                 
Total params: 35 (140.00 Byte)
Trainable params: 35 (140.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model = Sequential()
model.add(Dense(5, activation = 'linear', input_shape=(12,)))
model.add(Activation('relu'))
model.add(Dense(6, activation = 'tanh'))
model.add(Dense(10, activation = 'softmax'))
#two activationو one behind the other is not correct.

in keras activation is a layer on its own,
<br>not a function, For parallelization all concepts in keras, are represented in class form.

u can design a custom activation yourself and use it..

In [22]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 5)                 65        
                                                                 
 activation_1 (Activation)   (None, 5)                 0         
                                                                 
 dense_13 (Dense)            (None, 6)                 36        
                                                                 
 dense_14 (Dense)            (None, 10)                70        
                                                                 
Total params: 171 (684.00 Byte)
Trainable params: 171 (684.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.get_weights()

[array([[ 0.22201055,  0.02537668,  0.21383399,  0.4063052 , -0.14020565],
        [ 0.03924185,  0.05041456,  0.00983393,  0.34469467, -0.169184  ],
        [ 0.08926505, -0.18575296,  0.33674264, -0.04637986,  0.5797821 ],
        [ 0.25833386,  0.46617603, -0.41294307, -0.20531043, -0.36383545],
        [-0.24772081,  0.42895722,  0.45284104, -0.03359306,  0.39156878],
        [-0.3074092 , -0.47914004,  0.53167486, -0.09663892, -0.12639642],
        [ 0.1886276 , -0.42650074, -0.4019069 , -0.5878457 ,  0.43004417],
        [ 0.06539488, -0.16273361, -0.5592731 ,  0.05977029,  0.01602507],
        [ 0.41887248, -0.41758567, -0.317022  ,  0.5052402 , -0.04384691],
        [ 0.3383211 , -0.569614  ,  0.42680848, -0.54917496, -0.57681674],
        [ 0.15837061, -0.32744217, -0.16296208, -0.06125778, -0.06185663],
        [-0.38316232,  0.16102314, -0.5501932 , -0.5889502 , -0.4780848 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.01538533, -0.134444

12 input(feature), 5 neurons,this matrix doesnt change our architecture and doesnt show the true architecture.
<br>
it saves like this for parallelization.
<br>
weights are between -1 and 1, we must normalize data too.

## Solve A Real Example :
Iris Datasets
length and width of petal and sepal of 3 different flowers
number of instances : 150,
number of attributes: 4

In [24]:
from sklearn import datasets

In [25]:
iris = datasets.load_iris()

In [26]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

we want just data and target.

 'target_names': ['setosa', 'versicolor', 'virginica'] =[0,1,2]

In [27]:
data = iris['data']
target = iris['target']

In [28]:
data, target

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [32]:
model = Sequential()
model.add(Dense(units=4, activation='linear', input_shape=(4,)))
model.add(Dense(units=3, activation='linear'))

loss function and optimizer are in compile function.

In [34]:
model.compile(optimizer='sgd', loss= 'MSE',metrics='accuracy')

In [35]:
model.fit(x=data, y=target)

5/5 [==============================] - 1s 5ms/step - loss: 5.2713 - accuracy: 0.1533 


accuracy is zero, model learned nothing

take 1 data get one output compare with its target, then next data...

in each level optimization is done


add train test:

In [36]:
model.fit(x=data, y=target, batch_size=150) #vanilla gradient descent

1/1 [==============================] - 0s 16ms/step - loss: 1.1027 - accuracy: 0.1533


In [38]:
model.fit(x=data, y=target, batch_size=1) #stochastic gradient descent

150/150 [==============================] - 0s 2ms/step - loss: 0.1622 - accuracy: 0.2533


In [39]:
model.fit(x=data, y=target, batch_size=16) #mini batch gradient descent

10/10 [==============================] - 0s 3ms/step - loss: 0.0930 - accuracy: 0.2267


always we use mini batch...

epochs is like reading a book for two times.
if u did it more than enough, it may occurs overfittng and it memorize all the data(hefz kardan)

In [40]:
model.fit(x=data, y=target, batch_size=16, epochs=2)

Epoch 1/2
10/10 [==============================] - 0s 2ms/step - loss: 0.0920 - accuracy: 0.1800
Epoch 2/2
10/10 [==============================] - 0s 2ms/step - loss: 0.0950 - accuracy: 0.2333


In [41]:
y_hat = model.predict(data[:5])

1/1 [==============================] - 0s 100ms/step


predict takes list of data,input is list, they see the data in batch form

In [42]:
y_hat

array([[-0.02982447,  0.01072513,  0.06749995],
       [ 0.1358191 ,  0.09309595,  0.2632177 ],
       [-0.00639006,  0.02832051,  0.07236107],
       [ 0.08490202,  0.14188251,  0.15887602],
       [-0.08412006,  0.00180083, -0.0117843 ]], dtype=float32)

In [43]:
y_hat = model.predict(data[:1])

1/1 [==============================] - 0s 40ms/step


In [44]:
data[0], data[:1]

(array([5.1, 3.5, 1.4, 0.2]), array([[5.1, 3.5, 1.4, 0.2]]))